import { isLanguageCode } from '@bookswap/shared'

/**
 * Open Library encodes language as MARC (= ISO 639-2, mostly the /B form):
 * `/languages/eng`, `/languages/ukr`. This repository's domain (§4.4,
 * `languageCodeSchema`) settled on ISO 639-1 — two-letter codes — so the map
 * below converts three-letter MARC codes to two-letter ones. Where the two
 * forms (bibliographic/terminologic) diverge, both lead to the same ISO 639-1,
 * e.g. `ger`/`deu` → `de`.
 *
 * The list is the ISO 639-2 ↔ ISO 639-1 table, not a guess: a language absent
 * from it (e.g. `mul` — "multiple languages", `und` — "undetermined") stays
 * unnormalized — see §6.3 item 7: "leave an unknown value empty rather than
 * substituting an arbitrary default".
 */
export const ISO_639_2_TO_1: Readonly<Record<string, string>> = {
  aar: 'aa',
  abk: 'ab',
  ave: 'ae',
  afr: 'af',
  aka: 'ak',
  amh: 'am',
  arg: 'an',
  ara: 'ar',
  asm: 'as',
  ava: 'av',
  aym: 'ay',
  aze: 'az',
  bak: 'ba',
  bel: 'be',
  bul: 'bg',
  bih: 'bh',
  bis: 'bi',
  bam: 'bm',
  ben: 'bn',
  tib: 'bo',
  bod: 'bo',
  bre: 'br',
  bos: 'bs',
  cat: 'ca',
  che: 'ce',
  cha: 'ch',
  cos: 'co',
  cre: 'cr',
  cze: 'cs',
  ces: 'cs',
  chu: 'cu',
  chv: 'cv',
  wel: 'cy',
  cym: 'cy',
  dan: 'da',
  ger: 'de',
  deu: 'de',
  div: 'dv',
  dzo: 'dz',
  ewe: 'ee',
  gre: 'el',
  ell: 'el',
  eng: 'en',
  epo: 'eo',
  spa: 'es',
  est: 'et',
  baq: 'eu',
  eus: 'eu',
  per: 'fa',
  fas: 'fa',
  ful: 'ff',
  fin: 'fi',
  fij: 'fj',
  fao: 'fo',
  fre: 'fr',
  fra: 'fr',
  fry: 'fy',
  gle: 'ga',
  gla: 'gd',
  glg: 'gl',
  grn: 'gn',
  guj: 'gu',
  glv: 'gv',
  hau: 'ha',
  heb: 'he',
  hin: 'hi',
  hmo: 'ho',
  hrv: 'hr',
  hat: 'ht',
  hun: 'hu',
  arm: 'hy',
  hye: 'hy',
  her: 'hz',
  ina: 'ia',
  ind: 'id',
  ile: 'ie',
  ibo: 'ig',
  iii: 'ii',
  ipk: 'ik',
  ido: 'io',
  ice: 'is',
  isl: 'is',
  ita: 'it',
  iku: 'iu',
  jpn: 'ja',
  jav: 'jv',
  geo: 'ka',
  kat: 'ka',
  kon: 'kg',
  kik: 'ki',
  kua: 'kj',
  kaz: 'kk',
  kal: 'kl',
  khm: 'km',
  kan: 'kn',
  kor: 'ko',
  kau: 'kr',
  kas: 'ks',
  kur: 'ku',
  kom: 'kv',
  cor: 'kw',
  kir: 'ky',
  lat: 'la',
  ltz: 'lb',
  lug: 'lg',
  lim: 'li',
  lin: 'ln',
  lao: 'lo',
  lit: 'lt',
  lub: 'lu',
  lav: 'lv',
  mlg: 'mg',
  mah: 'mh',
  mao: 'mi',
  mri: 'mi',
  mac: 'mk',
  mkd: 'mk',
  mal: 'ml',
  mon: 'mn',
  mar: 'mr',
  may: 'ms',
  msa: 'ms',
  mlt: 'mt',
  bur: 'my',
  mya: 'my',
  nau: 'na',
  nob: 'nb',
  nde: 'nd',
  nep: 'ne',
  ndo: 'ng',
  dut: 'nl',
  nld: 'nl',
  nno: 'nn',
  nor: 'no',
  nbl: 'nr',
  nav: 'nv',
  nya: 'ny',
  oci: 'oc',
  oji: 'oj',
  orm: 'om',
  ori: 'or',
  oss: 'os',
  pan: 'pa',
  pli: 'pi',
  pol: 'pl',
  pus: 'ps',
  por: 'pt',
  que: 'qu',
  roh: 'rm',
  run: 'rn',
  rum: 'ro',
  ron: 'ro',
  rus: 'ru',
  kin: 'rw',
  san: 'sa',
  srd: 'sc',
  snd: 'sd',
  sme: 'se',
  sag: 'sg',
  sin: 'si',
  slo: 'sk',
  slk: 'sk',
  slv: 'sl',
  smo: 'sm',
  sna: 'sn',
  som: 'so',
  alb: 'sq',
  sqi: 'sq',
  srp: 'sr',
  ssw: 'ss',
  sot: 'st',
  sun: 'su',
  swe: 'sv',
  swa: 'sw',
  tam: 'ta',
  tel: 'te',
  tgk: 'tg',
  tha: 'th',
  tir: 'ti',
  tuk: 'tk',
  tgl: 'tl',
  tsn: 'tn',
  ton: 'to',
  tur: 'tr',
  tso: 'ts',
  tat: 'tt',
  twi: 'tw',
  tah: 'ty',
  uig: 'ug',
  ukr: 'uk',
  urd: 'ur',
  uzb: 'uz',
  ven: 've',
  vie: 'vi',
  vol: 'vo',
  wln: 'wa',
  wol: 'wo',
  xho: 'xh',
  yid: 'yi',
  yor: 'yo',
  zha: 'za',
  chi: 'zh',
  zho: 'zh',
  zul: 'zu',
}

/**
 * A three-letter MARC code → ISO 639-1. An unknown, empty or unexpectedly typed
 * code yields `undefined` rather than a thrown error: one corrupted field must
 * not fail the whole answer when the rest of it is usable.
 *
 * Shared by both Open Library paths — ISBN lookup
 * (`open-library-lookup-provider.ts`, where the code arrives as an object
 * `{ key: '/languages/eng' }`) and title search
 * (`../search/external/open-library-search-provider.ts`, where `search.json`
 * returns the same code as a plain string `'eng'`). The shapes differ, the
 * table is one — two hundred mappings are not worth keeping in two copies that
 * will drift apart.
 */
export function iso6391FromMarc(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined

  const marc = value.split('/').pop()?.trim().toLowerCase()
  if (marc === undefined || marc === '') return undefined

  const code = ISO_639_2_TO_1[marc]

  return code !== undefined && isLanguageCode(code) ? code : undefined
}
